[workspace]
name = "servicex-workshop"
version = "0.0.1"
description = "ServiceX ATLAS Workshop"
authors = ["Roger Janusiak <rogerja@uw.edu>", "Artur Cordeiro Oudot Choi <acordeir@cern.ch>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64"]

[tasks.lab]
description = "Start a JupyterLab instance"
cmd = "jupyter lab"

[tasks.start]
description = "Get started with the repository"
depends-on = ["lab"]

[dependencies]
python = "3.11.*"
ipykernel = "*"
notebook = ">=7.5.0,<8"
jupyterlab = ">=4.5.0,<5"
mplhep = ">=0.4.1,<0.5"
xrootd = ">=5.8.4,<6"
fsspec-xrootd = ">=0.5.1,<0.6"
ipywidgets = ">=8.1.7,<9"
awkward = ">=2.8.11,<3"
servicex = ">=3.2.3,<4"
uproot = ">=5.0.0" 
servicex-analysis-utils = ">=1.2.2,<2"
func_adl_servicex_xaodr25 = ">=2.4.5.25.2.41,<3"
vector = "*"
#coffea = ">=2025.10.1,<2026"
#atlas-schema = ">=0.4.1,<0.5"
#atlasopenmagic = ">=1.6.1,<2"